title: Mu Xuanmiao's Homepage
page-top-title: Mu Xuanmiao
top-section-bg-text: Welcome to My Homepage!
home-subtitle: Mu xuanmiao&ensp;|&ensp;Mu Xuanmiao
copyright-text: '&copy; Mu Xuanmiao. All Rights Reserved.'
